# Generated by Django 4.1.3 on 2022-11-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webservice',
            options={'managed': False, 'permissions': (('can_access_product_category', 'Can access product categories'), ('can_create_product_category', 'Can create product categories'), ('can_update_product_category', 'Can update product categories'), ('can_access_product', 'Can access products'))},
        ),
    ]
